CREATE DATABASE fullgas;
\c fullgas

CREATE TABLE "productos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "precio" integer DEFAULT 0,
  "marca" varchar DEFAULT 'sin marca',
  "formato" varchar DEFAULT 'sin formato',
  "tipo" varchar DEFAULT 'normal',
  "imagen" varchar DEFAULT 'https://picsum.photos/240',
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "publicaciones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "producto_id" integer NOT NULL,
  "titulo" varchar DEFAULT 'Titulo Publicacion',
  "descripcion" varchar DEFAULT 'Descripcion Publicacion',
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "compras" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "publicaciones_id" integer NOT NULL,
  "transaccion" varchar NOT NULL,
  "cantidad" integer NOT NULL,
  "precio_total" integer NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "favoritos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "publicaciones_id" integer NOT NULL,
  "status" boolean DEFAULT true,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "publicaciones" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");
ALTER TABLE "publicaciones" ADD FOREIGN KEY ("producto_id") REFERENCES "productos" ("id");
ALTER TABLE "compras" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");
ALTER TABLE "compras" ADD FOREIGN KEY ("publicaciones_id") REFERENCES "publicaciones" ("id");
ALTER TABLE "favoritos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");
ALTER TABLE "favoritos" ADD FOREIGN KEY ("publicaciones_id") REFERENCES "publicaciones" ("id");

-- Creacion de usuario
-- Crear desde Postman para encriptar contraseña

-- Creacion de productos
INSERT INTO productos VALUES
(DEFAULT, 11450, 'Gasco', '5Kg' , DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 16500, 'Gasco', '11Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 23450, 'Gasco', '15Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 60000, 'Gasco', '45Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 11450, 'Gasco', '5Kg' , 'catalitico' , DEFAULT , DEFAULT ),
(DEFAULT, 16500, 'Gasco', '11Kg', 'catalitico', DEFAULT , DEFAULT ),
(DEFAULT, 23450, 'Gasco', '15Kg', 'catalitico', DEFAULT , DEFAULT ),
(DEFAULT, 60000, 'Gasco', '45Kg', 'catalitico', DEFAULT , DEFAULT ),
(DEFAULT, 25800, 'Gasco', 'Grua Horquilla H15', DEFAULT, DEFAULT , DEFAULT ),
(DEFAULT, 69700, 'Gasco', 'Cilindro Completo 11Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 70100, 'Gasco', 'Cilindro Completo 15Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 172150, 'Gasco', 'Cilindro Completo 45Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 12490, 'Lipigas', '5Kg' , DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 18990, 'Lipigas', '11Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 23990, 'Lipigas', '15Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 74990, 'Lipigas', '45Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 16490, 'Lipigas', '11Kg Plus', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 29990, 'Lipigas', 'Grua Horquilla H15', DEFAULT, DEFAULT , DEFAULT ),
(DEFAULT, 12500, 'Abastible', '5Kg' , DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 15400, 'Abastible', '11Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 18700, 'Abastible', '15Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 78550, 'Abastible', '45Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 12500, 'Abastible', '5Kg' , 'catalitico' , DEFAULT , DEFAULT ),
(DEFAULT, 15400, 'Abastible', '11Kg', 'catalitico', DEFAULT , DEFAULT ),
(DEFAULT, 18700, 'Abastible', '15Kg', 'catalitico', DEFAULT , DEFAULT ),
(DEFAULT, 78550, 'Abastible', '45Kg', 'catalitico', DEFAULT , DEFAULT ),
(DEFAULT, 30850, 'Abastible', 'VMA 15Kg', DEFAULT , DEFAULT , DEFAULT ),
(DEFAULT, 29850, 'Abastible', 'VM 15Kg', DEFAULT , DEFAULT , DEFAULT );

--Creacion de publicaciones
INSERT INTO publicaciones VALUES
(DEFAULT, 1, 17, 'Gas Normal de 11 Kilos Plus','Más liviano, fácil de transportar y con un tamaño más conveniente', DEFAULT, DEFAULT ),
(DEFAULT, 1, 26, 'Gas Catalítico de 45 Kilos','Es ideal para su uso en artefactos al interior del hogar', DEFAULT, DEFAULT ),
(DEFAULT, 1, 2, 'Gas Normal de 11 Kilos', 'El Gas tradicional para el Hogar', DEFAULT, DEFAULT ),
(DEFAULT, 1, 4, 'Gas Normal de 45 Kilos','Evite comprar Gas por un buen tiempo', DEFAULT, DEFAULT ),
(DEFAULT, 1, 5, 'Gas Catalitico de 5 Kilos','De tamaño conveniente para nuestros clientes', DEFAULT, DEFAULT );

-- Creacion de compras
INSERT INTO compras VALUES
(DEFAULT, 1, 2, 'b04tx2bf', 2, 157100, DEFAULT),
(DEFAULT, 1, 3, 'b04tx2bf', 4, 66000, DEFAULT),
(DEFAULT, 1,  1, 'm90t9fch', 1, 16490, DEFAULT),
(DEFAULT, 1, 5, 'm90t9fch', 2, 22900, DEFAULT),
(DEFAULT, 1,  3, 'm90t9fch', 1, 23450, DEFAULT),
(DEFAULT, 1, 4, 'm90t9fch', 3, 180000, DEFAULT);